benchmark_id: nasbench201
search_space_id: nb201_topology
version: "1.1"
path: /path/to/data/nasbench201/NAS-Bench-201-v1_1-096897.pth
datasets: [cifar10-valid, cifar10, cifar100, ImageNet16-120]
epoch_budgets: [12, 200]
